"""Small, dependency-free importer for the PPR SysML v2 profile we emit.

This intentionally targets the portable and PPR-profiled surface generated by
``backend.sysml``.  It is not a general SysML compiler; unsupported constructs
are rejected with a useful error instead of being silently discarded.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from .model.core import Attribute
from .model.ppr import PprElement, PprModel, PprRelationship, validate_ppr_model


class SysmlImportError(ValueError):
    """Raised when a SysML document cannot be projected into PPR."""


_DECLARATION = re.compile(
    r"^(?:#(?P<meta>product|process|resource)\s+)?"
    r"(?:(?P<keyword>item|action|part)\s+)?(?P<definition>def\s+)?"
    r"(?:<(?P<symbol>[^>]+)>\s*)?"
    r"(?P<name>'(?:\\.|[^'])*'|[A-Za-z_][\w]*)"
    r"(?:\s*:\s*>?\s*(?P<type>[^\s{\[]+))?"
    r"(?P<multiplicity>\[[^]]+\])?\s*(?P<terminator>[{;])\s*$"
)
_ATTRIBUTE = re.compile(
    r"^attribute\s+(?:<[^>]+>\s*)?"
    r"(?P<name>'(?:\\.|[^'])*'|[A-Za-z_][\w]*)\s*:\s*"
    r"(?P<datatype>[A-Za-z_][\w:]*)\s*=\s*(?P<value>.+?)(?:\s*\[(?P<unit>[^]]+)\])?;\s*$"
)
_MODEL_PACKAGE = re.compile(r"^package\s+<[^>]+>\s+(?P<name>'(?:\\.|[^'])*'|\w+)")
_GROUPS = {"productOccurrences": "product", "processOccurrences": "process", "resourceOccurrences": "resource"}


@dataclass(frozen=True)
class _Decl:
    keyword: str
    ppr_type: str
    definition: bool
    symbol: str
    name: str
    type_ref: str | None
    multiplicity: str | None
    start: int
    end: int
    depth: int
    group: str | None


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1].replace("\\'", "'").replace("\\\\", "\\")
    return value


def _type_for(keyword: str) -> str:
    return {"item": "product", "action": "process", "part": "resource"}[keyword]


def _bounds(value: str | None) -> tuple[int | None, int | str | None]:
    if not value:
        return None, None
    raw = value[1:-1]
    if ".." not in raw:
        number = int(raw)
        return number, number
    low, high = raw.split("..", 1)
    return int(low), ("*" if high == "*" else int(high))


def _value(raw: str) -> str | int | float | bool:
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] == '"':
        return bytes(raw[1:-1], "utf-8").decode("unicode_escape")
    if raw == "true":
        return True
    if raw == "false":
        return False
    try:
        return int(raw)
    except ValueError:
        try:
            return float(raw)
        except ValueError:
            return raw


def _matching_brace(lines: list[str], start: int) -> int:
    depth = 0
    for index in range(start, len(lines)):
        depth += lines[index].count("{") - lines[index].count("}")
        if depth == 0:
            return index
    raise SysmlImportError("Unclosed SysML block")


def _parse_declarations(lines: list[str]) -> list[_Decl]:
    declarations: list[_Decl] = []
    depths: list[tuple[int, str | None]] = []
    depth = 0
    for index, raw in enumerate(lines):
        line = raw.strip()
        while depths and depth <= depths[-1][0]:
            depths.pop()
        group = next((name for _, name in reversed(depths) if name in _GROUPS), None)
        match = _DECLARATION.match(line)
        if match:
            keyword = match.group("keyword") or {"product": "item", "process": "action", "resource": "part"}.get(match.group("meta"))
            if keyword is None:
                depth += raw.count("{") - raw.count("}")
                continue
            terminator = match.group("terminator")
            end = _matching_brace(lines, index) if terminator == "{" else index
            declarations.append(
                _Decl(
                    keyword=keyword,
                    ppr_type=match.group("meta") or _type_for(keyword),
                    definition=bool(match.group("definition")),
                    symbol=match.group("symbol") or f"line_{index + 1}",
                    name=_unquote(match.group("name")),
                    type_ref=match.group("type"),
                    multiplicity=match.group("multiplicity"),
                    start=index,
                    end=end,
                    depth=depth,
                    group=group,
                )
            )
            if terminator == "{":
                declared_group = match.group("name") if match.group("name") in _GROUPS else None
                depths.append((depth, declared_group))
        depth += raw.count("{") - raw.count("}")
    return declarations


def _attributes(lines: list[str], declaration: _Decl) -> list[Attribute]:
    result: list[Attribute] = []
    depth = declaration.depth + 1
    current_depth = depth
    for index in range(declaration.start + 1, declaration.end):
        raw = lines[index]
        stripped = raw.strip()
        if not stripped:
            continue
        current_depth += raw.count("{") - raw.count("}")
        if current_depth != depth:
            continue
        match = _ATTRIBUTE.match(stripped)
        if not match:
            continue
        result.append(
            Attribute(
                id=f"attr_{declaration.symbol}_{len(result) + 1}",
                name=_unquote(match.group("name")),
                value=_value(match.group("value")),
                datatype=match.group("datatype"),
                unit=match.group("unit"),
            )
        )
    return result


def _description_and_attributes(
    lines: list[str], declaration: _Decl
) -> tuple[str, list[Attribute]]:
    attributes = _attributes(lines, declaration)
    description = next(
        (
            str(attribute.value)
            for attribute in attributes
            if attribute.name == "__ppr_description"
        ),
        "",
    )
    return description, [
        attribute
        for attribute in attributes
        if attribute.name != "__ppr_description"
    ]


_PORT = re.compile(
    r"^(?:in|out)\s+(?:item|action|part)\s+"
    r"(?P<name>[A-Za-z_][\w]*)\s*:\s*[^;\s\[]+"
    r"(?P<multiplicity>\[[^]]+\])?\s*(?P<terminator>;|{)"
)
_STANDALONE_DEFINITION = re.compile(
    r".*_standalone_definition(?:_[0-9a-f]{8})?$"
)
_NUMBER = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"


def _ports(
    lines: list[str], declaration: _Decl
) -> dict[str, tuple[int | None, int | str | None, float | None, str | None]]:
    result: dict[
        str, tuple[int | None, int | str | None, float | None, str | None]
    ] = {}
    for index, raw in enumerate(
        lines[declaration.start + 1 : declaration.end], start=declaration.start + 1
    ):
        match = _PORT.match(raw.strip())
        if match:
            lower_bound, upper_bound = _bounds(match.group("multiplicity"))
            quantity: float | None = None
            unit: str | None = None
            if match.group("terminator") == "{":
                body_end = _matching_brace(lines, index)
                body = " ".join(lines[index + 1 : body_end])
                quantity_match = re.search(
                    rf"requestedQuantity\s*:\s*Real\s*=\s*({_NUMBER})"
                    r"(?:\s*\[([^]]+)\])?",
                    body,
                )
                if quantity_match:
                    quantity = float(quantity_match.group(1))
                    unit = quantity_match.group(2)
            result[match.group("name")] = (
                lower_bound,
                upper_bound,
                quantity,
                unit,
            )
    return result


def _endpoint(path: str, paths: dict[str, PprElement]) -> tuple[PprElement, str | None]:
    path = path.strip().rstrip(";")
    parts = path.split(".")
    for size in range(len(parts), 0, -1):
        candidate = ".".join(parts[:size])
        if candidate in paths:
            return paths[candidate], (parts[-1] if size < len(parts) else None)
    for container in ("productOccurrences", "processOccurrences", "resourceOccurrences"):
        prefixed = f"{container}.{path}"
        if prefixed in paths:
            return paths[prefixed], None
    raise SysmlImportError(f"Cannot resolve SysML endpoint '{path}'")


def import_sysml(content: str) -> PprModel:
    """Project a portable or PPR-profiled SysML model into canonical PPR JSON."""
    if not content.strip():
        raise SysmlImportError("The SysML document is empty")
    lines = content.splitlines()
    declarations = _parse_declarations(lines)
    model_match = next((_MODEL_PACKAGE.match(line.strip()) for line in lines if _MODEL_PACKAGE.match(line.strip())), None)
    model_name = _unquote(model_match.group("name")) if model_match else "Imported SysML model"

    definitions: list[PprElement] = []
    definition_by_symbol: dict[str, PprElement] = {}
    standalone_definition_symbols: set[str] = set()
    reserved = {"Product", "Process", "Resource", "products", "processes", "resources"}
    for declaration in declarations:
        if not declaration.definition or declaration.name in reserved:
            continue
        if _STANDALONE_DEFINITION.fullmatch(declaration.symbol):
            standalone_definition_symbols.add(declaration.symbol)
            continue
        description, attributes = _description_and_attributes(lines, declaration)
        definition = PprElement(
            id=declaration.symbol,
            name=declaration.name,
            type=declaration.ppr_type,
            kind="definition",
            description=description,
            attributes=attributes,
            x=0,
            y=0,
        )
        definitions.append(definition)
        definition_by_symbol[declaration.symbol] = definition

    usages: list[PprElement] = []
    usage_decls = [item for item in declarations if not item.definition and item.group in _GROUPS]
    usage_by_decl: dict[_Decl, PprElement] = {}
    path_by_decl: dict[_Decl, str] = {}
    usage_bounds: dict[str, tuple[int | None, int | str | None]] = {}
    usage_ports: dict[
        str, dict[str, tuple[int | None, int | str | None, float | None, str | None]]
    ] = {}
    for declaration in usage_decls:
        ref = (declaration.type_ref or "").split("[")[0]
        definition = definition_by_symbol.get(ref)
        if definition is None and ref not in standalone_definition_symbols:
            raise SysmlImportError(f"Usage '{declaration.name}' references unknown definition '{ref}'")
        parents = [
            candidate
            for candidate in usage_decls
            if candidate.start < declaration.start < candidate.end
            and candidate.depth < declaration.depth
            and candidate.group == declaration.group
        ]
        parent = max(parents, key=lambda candidate: candidate.depth, default=None)
        container = declaration.group
        path = f"{container}.{declaration.symbol}"
        if parent:
            parent_path = path_by_decl[parent]
            path = f"{parent_path}.{declaration.symbol}"
        _low, _high = _bounds(declaration.multiplicity)
        if parent:
            usage_bounds[declaration.symbol] = (_low, _high)
        if declaration.ppr_type == "process":
            usage_ports[declaration.symbol] = _ports(lines, declaration)
        description, attributes = _description_and_attributes(lines, declaration)
        usage = PprElement(
            id=declaration.symbol,
            name=declaration.name,
            type=declaration.ppr_type,
            kind="usage",
            definition_id=definition.id if definition is not None else None,
            description=description,
            attributes=attributes,
            x=120 + (len(usages) % 4) * 220,
            y=120 + (len(usages) // 4) * 140,
        )
        usages.append(usage)
        usage_by_decl[declaration] = usage
        path_by_decl[declaration] = path

    paths = {path: usage for declaration, usage in usage_by_decl.items() for path in [path_by_decl[declaration]]}
    relationships: list[PprRelationship] = []
    for declaration, usage in usage_by_decl.items():
        parents = [
            candidate
            for candidate in usage_decls
            if candidate.start < declaration.start < candidate.end
            and candidate.depth < declaration.depth
            and candidate.group == declaration.group
        ]
        parent = max(parents, key=lambda candidate: candidate.depth, default=None)
        if parent:
            relationships.append(PprRelationship(
                id=f"contains_{usage.id}",
                source_id=usage_by_decl[parent].id,
                target_id=usage.id,
                kind="contains",
            ))
        current_depth = declaration.depth + 1
        for line in lines[declaration.start + 1 : declaration.end]:
            stripped = line.strip()
            if current_depth == declaration.depth + 1:
                perform = re.match(r"perform\s+([^;]+);", stripped)
                if perform:
                    target, _ = _endpoint(perform.group(1), paths)
                    relationships.append(PprRelationship(id=f"perform_{usage.id}_{target.id}", source_id=usage.id, target_id=target.id, kind="performs"))
            current_depth += line.count("{") - line.count("}")

    normalized = " ".join(lines)
    for match in re.finditer(r"allocation\s+<([^>]+)>\s+allocate\s+([^\s]+)\s+to\s+([^;]+);", normalized):
        process, _ = _endpoint(match.group(2), paths)
        resource, _ = _endpoint(match.group(3), paths)
        relationships.append(PprRelationship(id=match.group(1), source_id=resource.id, target_id=process.id, kind="performs", modality="supports"))
    for match in re.finditer(r"succession\s+<([^>]+)>\s+first\s+([^\s]+)\s+then\s+([^;]+);", normalized):
        source, _ = _endpoint(match.group(2), paths)
        target, _ = _endpoint(match.group(3), paths)
        relationships.append(PprRelationship(id=match.group(1), source_id=source.id, target_id=target.id, kind="succeeds"))
    for match in re.finditer(r"flow\s+<([^>]+)>(?P<payload>.*?)\s+from\s+([^\s]+)\s+to\s+([^;{]+)(?:\s*\{(?P<body>.*?)\})?\s*;?", normalized):
        source, source_role = _endpoint(match.group(3), paths)
        target, target_role = _endpoint(match.group(4), paths)
        payload = match.group("payload")
        if " of " in payload:
            # Older exports used direct product-to-product transfer flows. They
            # cannot be represented honestly without a transforming process.
            continue
        kind = "consumed_by" if source.type == "product" and target.type == "process" else "produces"
        body = match.group("body") or ""
        quantity_match = re.search(
            rf"requestedQuantity\s*:\s*Real\s*=\s*({_NUMBER})"
            r"(?:\s*\[([^]]+)\])?",
            body,
        )
        quantity = float(quantity_match.group(1)) if quantity_match else None
        unit = quantity_match.group(2) if quantity_match else None
        lower_bound: int | None = None
        upper_bound: int | str | None = None
        transfer_bounds = re.search(r"\bof\s+[^\s\[]+(?:\[(?P<bounds>[^]]+)\])?", payload)
        if transfer_bounds and transfer_bounds.group("bounds"):
            lower_bound, upper_bound = _bounds(f"[{transfer_bounds.group('bounds')}]")
        role_name = target_role or source_role
        port_owner = target.id if kind == "consumed_by" else source.id
        if kind in {"consumed_by", "produces"}:
            port = usage_ports.get(port_owner, {}).get(role_name or "")
            if port is not None:
                lower_bound, upper_bound, port_quantity, port_unit = port
                if port_quantity is not None:
                    quantity = port_quantity
                    unit = port_unit
        relationships.append(PprRelationship(id=match.group(1), source_id=source.id, target_id=target.id, kind=kind, role_name=role_name, quantity=quantity, unit=unit, lower_bound=lower_bound, upper_bound=upper_bound))

    model = PprModel(name=model_name, library={"definitions": definitions}, diagram={"usages": usages, "relationships": relationships})
    result = validate_ppr_model(model)
    errors = [
        (
            f"relationship '{issue.relationship_id}'"
            if issue.relationship_id
            else f"element '{issue.element_id}'"
            if issue.element_id
            else "model"
        )
        + f": {issue.message}"
        for issue in result.issues
        if issue.severity == "error"
    ]
    if errors:
        raise SysmlImportError("Imported SysML is not a valid PPR model: " + "; ".join(errors))
    return model
